name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production --base-href="/myblueApp/"

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages \
            --dir=dist/myblue-app/browser \
            --name="tarunvemasani" \
            --email="tarunvemasani454@gmail.com" \
            --repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" \
            --no-silent
