name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or 'master' based on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js (use version compatible with Angular)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build Angular app
      - name: Build Angular App
        run: |
          npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"

      # 5. Deploy to GitHub Pages using angular-cli-ghpages
      - name: Setup Git Config (for angular-cli-ghpages)
        run: |
        git config user.name "tarunvemasani"
        git config user.email "tarunvemasani454@gmail.com"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/myblue-app/browser
